### PR TITLE
Free palenstine

### PR DESCRIPTION
**Pull request by CoonBalls3335**
This will fix everything. 😮

### CODE REVIEW

**Comment by CoonBalls3335** [comment]
Bruh not cool

**Comment by CoonBalls3335** [comment]
Im banning you you stupid nigger

**Comment by johnfortnitekennedyG** [comment]
you didnt use your alt account retard

**Comment by CoonBalls3335** [comment]
KYS NIGGER

**Comment by CoonBalls3335** [comment]
I DON'T CARE BLAH BLAH BLAH

**Comment by CoonBalls3335** [comment]
👨‍👧‍👧

**Comment by johnfortnitekennedyG** [comment]
[ PLOPPY ASSAULT IN PROGRESS // :poop::poop::poop::poop: //]
[AULT IN PROGRESS // :poop::poop::poop::poop: // PLOPPY ASS]
[GRESS // :poop::poop::poop::poop: // PLOPPY ASSAULT IN PRO]
[:poop::poop::poop: // PLOPPY ASSAULT IN PROGRESS // :poop:]

**Comment by CoonBalls3335** [comment]
Mistype

**Comment by CoonBalls3335** [comment]
[ I hate niggas i hate niggasASSAULT IN PROGRESS // 💩💩💩💩 //]
[AULT IN PROGRESS // 💩💩💩💩 // PLOPPY ASS]
[GRESS // 💩💩💩💩 // PLOPPY ASSAULT IN PRO]
[💩💩💩 // PLOPPY ASSAULT IN PROGRESS // 💩]

**Comment by CoonBalls3335** [comment]
[https://www.youtube.com/watch?v=hkfzIIhI0Tc](url)

**Comment by johnfortnitekennedyG** [comment]
Notice not the care not the care

**Comment by killthemallpewdiepie** [comment]
That was uncalled for

**Comment by killthemallpewdiepie** [comment]
That was uncalled for

**Comment by johnfortnitekennedyG** [comment]
Fixed

**Pull request closed without merging**
